const localization = {
    EN: {
        locale: 'EN',
        addCluster: "Add cluster",
        editCluster: "Edit cluster",
        deleteCluster: "Delete cluster",
        confirm: "Confirm",
        selectCluster: "Select a cluster",
        name: "Name",
        city: "City",
        type: "Type",
        latitude: "Latitude",
        longitude: "Longitude",
        workFrom: "Work from",
        workTo: "Work to",
        allFieldsMustBeFilled: "All fields must be filled out",
        allClusters: "All Clusters",
        allStorages: "All Storages",
        number: "Number",
        price: "Price",
        cluster: "Cluster",
        isOpened: "Is Opened",
        volumes: "Volumes",
        addStorage: "Add Storage",
        editStorage: "Edit Storage",
        deleteStorage: "Delete Storage",
        selectStorage: "Select a storage",
        addVolume: "Add Volume",
        editVolume: "Edit Volume",
        height: "Height",
        width: "Width",
        length: "Length",
        unit: "Unit",
        meters: "Meters",
        feet: "Feet",
        yard: "Yard",
        inch: "Inch",
        yes: "Yes",
        no: "No",
        allUsers: "All Users",
        email: "Email",
        role: "Role",
        username: "Username",
        changeRole: "Change Role",
        user: "User",
        staff: "Staff",
        admin: "Admin",
        exportData: "Export Data",
        importData: "Import Data",
        selectUserAlert: "Select a user to change their role.",
        roleUpdated: "User role updated successfully.",
        roleUpdateFailed: "Failed to change user role.",
        exportFailed: "Failed to export data.",
        importSuccess: "Data imported successfully.",
        importFailed: "Failed to import data.",
        changeStoragePrice: "Change Storage Price",
        storage: "Storage",
        allStoragesInCluster: "All storages in the cluster",
        changePrice: "Change Price",
        clusterStatistics: "Cluster Statistics",
        storageNumber: "Storage Number",
        rentedHours: "Rented Hours",
        earnings: "Earnings",
        providePriceAlert: "Please provide the price and select a cluster.",
        priceUpdated: "Price updated successfully.",
        priceUpdateFailed: "Failed to change price.",
        showForm: "Show Form",
        hideForm: "Hide Form",
        showStatistics: "Show Statistics",
        hideStatistics: "Hide Statistics",
        activeRentals: "Active Rentals",
        id: "ID",
        from: "From",
        to: "To",
        loading: "Loading...",
        fetchError: "Error fetching active rentals",
        bookingHistory: "Booking History",
        fetchError2: "Error fetching booking history",
        createAccount: "Account create",
        password: "Password",
        repeatPassword: "Repeat password",
        submit: "Submit",
        alreadyHaveAccount: "Already have an account?",
        login: "Login",
        noAccount: "Do not have an account?",
        register: "Register!",
        loadError: "Error loading cluster data",
        clusters: "Clusters",
        workTime: "Work Time",
        showStorages: "Show Storages",
        hideStorages: "Hide Storages",
        storages: "Storages",
        isBooked: "Booked",
        volume: "Volume",
        storageError: "Error fetching storage data",
        appName: "RentStorage",
        account: "Account",
        administration: "Administration",
        authorization: "Authorization",
        hello: "Hello",
        exitPrompt: "Do you want to exit?",
        balance: "Balance",
        replenishBalance: "Replenish Balance",
        enterAmount: "Enter amount",
        replenish: "Replenish",
        cancel: "Cancel",
        book:"Reserve",
        exportSuccess:"Export Success"
    },
    UK: {
        locale: 'UK',
        addCluster: "Додати кластер",
        editCluster: "Редагувати кластер",
        deleteCluster: "Видалити кластер",
        confirm: "Підтвердити",
        selectCluster: "Виберіть кластер",
        name: "Назва",
        city: "Місто",
        type: "Тип",
        latitude: "Широта",
        longitude: "Довгота",
        workFrom: "Працює з",
        workTo: "Працює до",
        allFieldsMustBeFilled: "Всі поля повинні бути заповнені",
        allClusters: "Всі Кластери",
        allStorages: "Всі Сховища",
        number: "Номер",
        price: "Ціна",
        cluster: "Кластер",
        isOpened: "Відкрито",
        volumes: "Об'єми",
        addStorage: "Додати Сховище",
        editStorage: "Редагувати Сховище",
        deleteStorage: "Видалити Сховище",
        selectStorage: "Виберіть сховище",
        addVolume: "Додати Об'єм",
        editVolume: "Редагувати Об'єм",
        height: "Висота",
        width: "Ширина",
        length: "Довжина",
        unit: "Одиниця",
        meters: "Метри",
        feet: "Фути",
        yard: "Ярд",
        inch: "Дюйм",
        yes: "Так",
        no: "Ні",
        allUsers: "Всі Користувачі",
        email: "Електронна пошта",
        role: "Роль",
        username: "Ім'я користувача",
        changeRole: "Змінити Роль",
        user: "Користувач",
        staff: "Персонал",
        admin: "Адміністратор",
        exportData: "Експортувати Дані",
        importData: "Імпортувати Дані",
        selectUserAlert: "Виберіть користувача, щоб змінити його роль.",
        roleUpdated: "Роль користувача успішно оновлена.",
        roleUpdateFailed: "Не вдалося змінити роль користувача.",
        exportFailed: "Не вдалося експортувати дані.",
        importSuccess: "Дані успішно імпортовані.",
        importFailed: "Не вдалося імпортувати дані.",
        changeStoragePrice: "Змінити Ціну Сховища",
        storage: "Сховище",
        allStoragesInCluster: "Всі сховища в кластері",
        changePrice: "Змінити Ціну",
        clusterStatistics: "Статистика Кластеру",
        storageNumber: "Номер Сховища",
        rentedHours: "Орендовані Години",
        earnings: "Заробіток",
        providePriceAlert: "Будь ласка, вкажіть ціну та виберіть кластер.",
        priceUpdated: "Ціну успішно оновлено.",
        priceUpdateFailed: "Не вдалося змінити ціну.",
        showForm: "Показати Форму",
        hideForm: "Сховати Форму",
        showStatistics: "Показати Статистику",
        hideStatistics: "Сховати Статистику",
        activeRentals: "Активні Оренди",
        id: "ID",
        from: "З",
        to: "До",
        loading: "Завантаження...",
        fetchError: "Помилка завантаження активних оренд",
        bookingHistory: "Історія Бронювань",
        fetchError2: "Помилка завантаження історії бронювань",
        createAccount: "Створити акаунт",
        password: "Пароль",
        repeatPassword: "Повторіть пароль",
        submit: "Підтвердити",
        alreadyHaveAccount: "Вже маєте акаунт?",
        login: "Увійти",
        noAccount: "Не маєте акаунта?",
        register: "Зареєструватися!",
        loadError: "Помилка завантаження даних про кластери",
        clusters: "Кластери",
        workTime: "Робочий час",
        showStorages: "Показати сховища",
        hideStorages: "Сховати сховища",
        storages: "Сховища",
        isBooked: "Заброньовано",
        volume: "Об'єм",
        storageError: "Помилка отримання даних про сховища",
        appName: "RentStorage",
        account: "Акаунт",
        administration: "Адміністрування",
        authorization: "Авторизація",
        hello: "Привіт",
        exitPrompt: "Ви хочете вийти?",
        balance: "Баланс",
        replenishBalance: "Поповнити баланс",
        enterAmount: "Введіть суму",
        replenish: "Поповнити",
        cancel: "Скасувати",
        book:"Забронювати",
        exportSuccess:"Експорт успішний"
    }
};

export default localization;