//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apz_pzpi_21_7_vysochyn_illia_task3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apz_pzpi_21_7_vysochyn_illia_task3.Properties.main", typeof(main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string ButtonRent {
            get {
                return ResourceManager.GetString("ButtonRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Cost for this amount of hours: .
        /// </summary>
        internal static string HoursCosts {
            get {
                return ResourceManager.GetString("HoursCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green numbers represent available storage for rent. Red represents closed and reserved storages, and purple represents storages reserved but open until the end of the storage lease. To open a storage before the end of the lease, you need to make a reservation using the RentStorage mobile application..
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of storage: .
        /// </summary>
        internal static string NumberOfStorage {
            get {
                return ResourceManager.GetString("NumberOfStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with terminal below and take a one time ticket for opening a storage..
        /// </summary>
        internal static string PayWithTerminal {
            get {
                return ResourceManager.GetString("PayWithTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour`s count: .
        /// </summary>
        internal static string PriceForHour {
            get {
                return ResourceManager.GetString("PriceForHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for renting: .
        /// </summary>
        internal static string PriceForRenting {
            get {
                return ResourceManager.GetString("PriceForRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent from.
        /// </summary>
        internal static string RentFrom {
            get {
                return ResourceManager.GetString("RentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent to.
        /// </summary>
        internal static string RentTo {
            get {
                return ResourceManager.GetString("RentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your renting! Take the ticket below..
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume of storage: .
        /// </summary>
        internal static string VolumeOfStorage {
            get {
                return ResourceManager.GetString("VolumeOfStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work from: .
        /// </summary>
        internal static string WorkFrom {
            get {
                return ResourceManager.GetString("WorkFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work to: .
        /// </summary>
        internal static string WorkTo {
            get {
                return ResourceManager.GetString("WorkTo", resourceCulture);
            }
        }
    }
}
